language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - "pip install --upgrade setuptools"
  - "pip install --upgrade enum34"
  - "pip install pycodestyle"
  - "pip install nose"
  - "pip install -r requirements.txt"
script:
  - ./.travis-setup.sh
  - ./test.sh
